development:
  adapter: postgresql
  encoding: unicode
  database: gopi_development
  username: 
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: gopi_test
  username: 
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: gopi_production
  username:
  password: