development:
  adapter: postgresql
  encoding: unicode
  database: gopi_development
  pool: 5
  username: postgres
  password: postgres
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: gopi_test
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: gopi_production
  pool: 5
  username: postgres
  password: postgres
