development:
  adapter: postgresql
  encoding: unicode
  database: gopi_development
  username: postgres
  password: postgres
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: gopi_test
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: gopi_production
  username: postgres
  password: postgres